[[Keyutils]]
arch = "aarch64"
git-tree-sha1 = "f08e78cee441d9edad9c07bd61f15f72ac094da2"
libc = "glibc"
os = "linux"

    [[Keyutils.download]]
    sha256 = "77ac3a7210757bbfa880550be8b33a8c3f76b50743a75727eaf5bc32d5ca6a48"
    url = "https://github.com/JuliaBinaryWrappers/Keyutils_jll.jl/releases/download/Keyutils-v1.6.1+2/Keyutils.v1.6.1.aarch64-linux-gnu.tar.gz"
[[Keyutils]]
arch = "aarch64"
git-tree-sha1 = "0032e27e531542353375d8ff1580d096cc8250d6"
libc = "musl"
os = "linux"

    [[Keyutils.download]]
    sha256 = "e454e2162c0aaaecb8211a0535668a898ba08079d976aa6018837a91757cf683"
    url = "https://github.com/JuliaBinaryWrappers/Keyutils_jll.jl/releases/download/Keyutils-v1.6.1+2/Keyutils.v1.6.1.aarch64-linux-musl.tar.gz"
[[Keyutils]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "303997dec69b15430e4eace3769233a6a6d851d4"
libc = "glibc"
os = "linux"

    [[Keyutils.download]]
    sha256 = "8eb549b92d9a06fc113bba225753c62465ea0ec6890e7ae54548a3192ddac89f"
    url = "https://github.com/JuliaBinaryWrappers/Keyutils_jll.jl/releases/download/Keyutils-v1.6.1+2/Keyutils.v1.6.1.armv7l-linux-gnueabihf.tar.gz"
[[Keyutils]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "952474bb5e9ee9b1a1ffde1704eec0317651158a"
libc = "musl"
os = "linux"

    [[Keyutils.download]]
    sha256 = "9d7f24a7b7520bede1169454c71e664d10728719710dccf36c44dedf573f0f2d"
    url = "https://github.com/JuliaBinaryWrappers/Keyutils_jll.jl/releases/download/Keyutils-v1.6.1+2/Keyutils.v1.6.1.armv7l-linux-musleabihf.tar.gz"
[[Keyutils]]
arch = "i686"
git-tree-sha1 = "3202b341cdbf96aaf37bbaae5955c4fe8d09ae30"
libc = "glibc"
os = "linux"

    [[Keyutils.download]]
    sha256 = "a0117b5131abfff60519c721edfdd5fb12dc54cc6f3494650ad085c52177747b"
    url = "https://github.com/JuliaBinaryWrappers/Keyutils_jll.jl/releases/download/Keyutils-v1.6.1+2/Keyutils.v1.6.1.i686-linux-gnu.tar.gz"
[[Keyutils]]
arch = "i686"
git-tree-sha1 = "0b2f794279316764c7b4e0bb72c005fa543d239f"
libc = "musl"
os = "linux"

    [[Keyutils.download]]
    sha256 = "d14c3acb8cade9ea3a4cc09162a700754b36b6ab3b03bead878b5c1860cc23c2"
    url = "https://github.com/JuliaBinaryWrappers/Keyutils_jll.jl/releases/download/Keyutils-v1.6.1+2/Keyutils.v1.6.1.i686-linux-musl.tar.gz"
[[Keyutils]]
arch = "powerpc64le"
git-tree-sha1 = "778b390f98f1129ae218f6c9b87c6051bb37c864"
libc = "glibc"
os = "linux"

    [[Keyutils.download]]
    sha256 = "dee45520abe06959820ef078ba0b508ddd9775e40f2b66f409d36994f4d02164"
    url = "https://github.com/JuliaBinaryWrappers/Keyutils_jll.jl/releases/download/Keyutils-v1.6.1+2/Keyutils.v1.6.1.powerpc64le-linux-gnu.tar.gz"
[[Keyutils]]
arch = "x86_64"
git-tree-sha1 = "f88e1d12b4915425efaa6d0f20d76d304d8eda71"
libc = "glibc"
os = "linux"

    [[Keyutils.download]]
    sha256 = "017859368d01bfb930508a92f7eb0bc6b613b9e48e7f4f55de20da07b4658819"
    url = "https://github.com/JuliaBinaryWrappers/Keyutils_jll.jl/releases/download/Keyutils-v1.6.1+2/Keyutils.v1.6.1.x86_64-linux-gnu.tar.gz"
[[Keyutils]]
arch = "x86_64"
git-tree-sha1 = "e82eb2771005a1f39f6688a908277f38064fb374"
libc = "musl"
os = "linux"

    [[Keyutils.download]]
    sha256 = "83f8d8b52fe2b47d3dfbf92015057adf586e4f4f12b0996f958afea02af49f42"
    url = "https://github.com/JuliaBinaryWrappers/Keyutils_jll.jl/releases/download/Keyutils-v1.6.1+2/Keyutils.v1.6.1.x86_64-linux-musl.tar.gz"
