[[Keyutils]]
arch = "aarch64"
git-tree-sha1 = "2dc343f5a01903576b75d631de72d04c452a0046"
libc = "glibc"
os = "linux"

    [[Keyutils.download]]
    sha256 = "47c6f00526190534a98e0fffd4bdbc750b4ee08fbb27e4954e0d342d627e5abb"
    url = "https://github.com/JuliaBinaryWrappers/Keyutils_jll.jl/releases/download/Keyutils-v1.6.3+0/Keyutils.v1.6.3.aarch64-linux-gnu.tar.gz"
[[Keyutils]]
arch = "aarch64"
git-tree-sha1 = "b250cb90ae4e27f6c26069d0d7bc8485b638ea5b"
libc = "musl"
os = "linux"

    [[Keyutils.download]]
    sha256 = "1e052fffb355ed462796a20eceefcd7a1388c5f3507e7eb90ea3cde4ef8d86e4"
    url = "https://github.com/JuliaBinaryWrappers/Keyutils_jll.jl/releases/download/Keyutils-v1.6.3+0/Keyutils.v1.6.3.aarch64-linux-musl.tar.gz"
[[Keyutils]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6094cfe6652a1e89bdc66562dfde594b60e8a2ab"
libc = "glibc"
os = "linux"

    [[Keyutils.download]]
    sha256 = "9b1c892532c02488f381bd37edcc2282577bf83b209a005beacc0203987f3924"
    url = "https://github.com/JuliaBinaryWrappers/Keyutils_jll.jl/releases/download/Keyutils-v1.6.3+0/Keyutils.v1.6.3.armv6l-linux-gnueabihf.tar.gz"
[[Keyutils]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "502458690449f1b8fad99f89345121e9527e7ad4"
libc = "musl"
os = "linux"

    [[Keyutils.download]]
    sha256 = "8c6f756be4a5c42948d54abe0d517192bf05cf6cbd7f2b9f5b6ee7a3e5741938"
    url = "https://github.com/JuliaBinaryWrappers/Keyutils_jll.jl/releases/download/Keyutils-v1.6.3+0/Keyutils.v1.6.3.armv6l-linux-musleabihf.tar.gz"
[[Keyutils]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6369fd2737cbfd1602410f5d4396b297e5c5da40"
libc = "glibc"
os = "linux"

    [[Keyutils.download]]
    sha256 = "fff33a59931da9d4a0a322729438bdcd273e24bcdf8a67e7bf4604bbf1dd976c"
    url = "https://github.com/JuliaBinaryWrappers/Keyutils_jll.jl/releases/download/Keyutils-v1.6.3+0/Keyutils.v1.6.3.armv7l-linux-gnueabihf.tar.gz"
[[Keyutils]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "491381a37d1b31b0b51922d0bffdb285579c793f"
libc = "musl"
os = "linux"

    [[Keyutils.download]]
    sha256 = "a6fd4f00e10efe2405aa1289480d1414517946fc469330f1a83859dfac52eea9"
    url = "https://github.com/JuliaBinaryWrappers/Keyutils_jll.jl/releases/download/Keyutils-v1.6.3+0/Keyutils.v1.6.3.armv7l-linux-musleabihf.tar.gz"
[[Keyutils]]
arch = "i686"
git-tree-sha1 = "9cda4ad852235769301de668cdf4142ef46d4731"
libc = "glibc"
os = "linux"

    [[Keyutils.download]]
    sha256 = "ae34a54f67d29a5c001444f301e6e934dbce7fb9f4b2ef91887787e37d208df1"
    url = "https://github.com/JuliaBinaryWrappers/Keyutils_jll.jl/releases/download/Keyutils-v1.6.3+0/Keyutils.v1.6.3.i686-linux-gnu.tar.gz"
[[Keyutils]]
arch = "i686"
git-tree-sha1 = "3fcd50e9c39703549670ebfefff254e68778116c"
libc = "musl"
os = "linux"

    [[Keyutils.download]]
    sha256 = "c62168f773c2ad91d7d8c19338fc68a759d7a19bd45af5c975ef9e8a1d7507ad"
    url = "https://github.com/JuliaBinaryWrappers/Keyutils_jll.jl/releases/download/Keyutils-v1.6.3+0/Keyutils.v1.6.3.i686-linux-musl.tar.gz"
[[Keyutils]]
arch = "powerpc64le"
git-tree-sha1 = "09637dd1003e80738441da3b4c4cbe7b842d007c"
libc = "glibc"
os = "linux"

    [[Keyutils.download]]
    sha256 = "1850eb189214ceb194a47be9e6e6d92d5a1d9ef1a33d32408c02b4b24ed96b66"
    url = "https://github.com/JuliaBinaryWrappers/Keyutils_jll.jl/releases/download/Keyutils-v1.6.3+0/Keyutils.v1.6.3.powerpc64le-linux-gnu.tar.gz"
[[Keyutils]]
arch = "x86_64"
git-tree-sha1 = "ce58b55734f76b4e483957548eb1631cd96d09f3"
libc = "glibc"
os = "linux"

    [[Keyutils.download]]
    sha256 = "47293147f9c5f0a6815a124ee817dda5f19ae6a087b6d738bdf8de8d026c9f2e"
    url = "https://github.com/JuliaBinaryWrappers/Keyutils_jll.jl/releases/download/Keyutils-v1.6.3+0/Keyutils.v1.6.3.x86_64-linux-gnu.tar.gz"
[[Keyutils]]
arch = "x86_64"
git-tree-sha1 = "d4d37326e7d4bc68d71e95a3f3f66c3314007296"
libc = "musl"
os = "linux"

    [[Keyutils.download]]
    sha256 = "0f47006f57f92e90bfd80321298823f1eae8ffb52b21bc6a29a8f6b109311411"
    url = "https://github.com/JuliaBinaryWrappers/Keyutils_jll.jl/releases/download/Keyutils-v1.6.3+0/Keyutils.v1.6.3.x86_64-linux-musl.tar.gz"
