[[Keyutils]]
arch = "armv7l"
git-tree-sha1 = "2e271ac7728f3f0ebafafd12837bde9fa180aa4f"
libc = "glibc"
os = "linux"

    [[Keyutils.download]]
    sha256 = "db2d12ceaa1cfc166151d4d7465bca5e9e88c93e4dcb23755d52dbd18f87d23e"
    url = "https://github.com/JuliaBinaryWrappers/Keyutils_jll.jl/releases/download/Keyutils-v1.6.1+0/Keyutils.v1.6.1.arm-linux-gnueabihf.tar.gz"
[[Keyutils]]
arch = "aarch64"
git-tree-sha1 = "f0e6d994596e6743b1fd3f0638f243050cac6e5b"
libc = "musl"
os = "linux"

    [[Keyutils.download]]
    sha256 = "0c9058c6d198096627bea99cd982548d7a42bfa0ab97a2fcc3fa9f19ed753410"
    url = "https://github.com/JuliaBinaryWrappers/Keyutils_jll.jl/releases/download/Keyutils-v1.6.1+0/Keyutils.v1.6.1.aarch64-linux-musl.tar.gz"
[[Keyutils]]
arch = "i686"
git-tree-sha1 = "cbbf77b85110fb44ba460cf12920780f735d123c"
libc = "musl"
os = "linux"

    [[Keyutils.download]]
    sha256 = "0e6083ce1a71427d78058f6348c5d219ab283ff32f24f02b2d8739006937be51"
    url = "https://github.com/JuliaBinaryWrappers/Keyutils_jll.jl/releases/download/Keyutils-v1.6.1+0/Keyutils.v1.6.1.i686-linux-musl.tar.gz"
[[Keyutils]]
arch = "i686"
git-tree-sha1 = "e94505c8d2584e25a9c48f535c168840024e9059"
libc = "glibc"
os = "linux"

    [[Keyutils.download]]
    sha256 = "c953b6f23497fdb7ab0ffa9d987b3815c374dc0d02757f233bf5a28e5cfe8151"
    url = "https://github.com/JuliaBinaryWrappers/Keyutils_jll.jl/releases/download/Keyutils-v1.6.1+0/Keyutils.v1.6.1.i686-linux-gnu.tar.gz"
[[Keyutils]]
arch = "powerpc64le"
git-tree-sha1 = "b021d0248ac3ed8a4f24bdbdd635ef0292771411"
libc = "glibc"
os = "linux"

    [[Keyutils.download]]
    sha256 = "29bd6b69198f68be08a59c333e0426d754f569a8c0ca2e97438c9042bfd6ad8f"
    url = "https://github.com/JuliaBinaryWrappers/Keyutils_jll.jl/releases/download/Keyutils-v1.6.1+0/Keyutils.v1.6.1.powerpc64le-linux-gnu.tar.gz"
[[Keyutils]]
arch = "armv7l"
git-tree-sha1 = "df3e961b79a0e171ea6b0d9ca218c15bcc7bc75c"
libc = "musl"
os = "linux"

    [[Keyutils.download]]
    sha256 = "8ca298447d083966b576cf68589cb261ada3338c65d7bbec009634d5d0ecd8a3"
    url = "https://github.com/JuliaBinaryWrappers/Keyutils_jll.jl/releases/download/Keyutils-v1.6.1+0/Keyutils.v1.6.1.arm-linux-musleabihf.tar.gz"
[[Keyutils]]
arch = "aarch64"
git-tree-sha1 = "f091e5f3ddbbb1ca4e2158a788cd095c0152bc4d"
libc = "glibc"
os = "linux"

    [[Keyutils.download]]
    sha256 = "e8d09c3c739617633ac41be83dcf41b86a0ce01678cab8c39d3512ab8a072a04"
    url = "https://github.com/JuliaBinaryWrappers/Keyutils_jll.jl/releases/download/Keyutils-v1.6.1+0/Keyutils.v1.6.1.aarch64-linux-gnu.tar.gz"
[[Keyutils]]
arch = "x86_64"
git-tree-sha1 = "10e0ca476e253a9ef5c091639ffc1fca25f968cf"
libc = "glibc"
os = "linux"

    [[Keyutils.download]]
    sha256 = "e8449e873cca2160deffc131745ec62d88c236294997408d3455d95dc84afd33"
    url = "https://github.com/JuliaBinaryWrappers/Keyutils_jll.jl/releases/download/Keyutils-v1.6.1+0/Keyutils.v1.6.1.x86_64-linux-gnu.tar.gz"
[[Keyutils]]
arch = "x86_64"
git-tree-sha1 = "b6f3842f2df904cb6f6d0a4609242671574c8af5"
libc = "musl"
os = "linux"

    [[Keyutils.download]]
    sha256 = "ceea823a0c2bf43e3ba9c2777302d81aa6c61f324b9717076c8a586ee1498687"
    url = "https://github.com/JuliaBinaryWrappers/Keyutils_jll.jl/releases/download/Keyutils-v1.6.1+0/Keyutils.v1.6.1.x86_64-linux-musl.tar.gz"
