[[Keyutils]]
arch = "armv7l"
git-tree-sha1 = "1f6971a8207794834fd35b9c2e92362e2c805ebb"
libc = "glibc"
os = "linux"

    [[Keyutils.download]]
    sha256 = "6ad1251f307e7caffc19be3fb202fa9aeb0be953e5f1625a4ffeeb4cde3b3a0b"
    url = "https://github.com/JuliaBinaryWrappers/Keyutils_jll.jl/releases/download/Keyutils-v1.6.1+0/Keyutils.v1.6.1.arm-linux-gnueabihf.tar.gz"
[[Keyutils]]
arch = "aarch64"
git-tree-sha1 = "d30ce6a3ddc398a744620472e68496e2564c2488"
libc = "musl"
os = "linux"

    [[Keyutils.download]]
    sha256 = "1a52ac20193e7c35beab9860e2ccdcf8986cca84861e6a1f1538a25099e1ca90"
    url = "https://github.com/JuliaBinaryWrappers/Keyutils_jll.jl/releases/download/Keyutils-v1.6.1+0/Keyutils.v1.6.1.aarch64-linux-musl.tar.gz"
[[Keyutils]]
arch = "i686"
git-tree-sha1 = "c2a0d610b9a80233615d186856c0c1b1f9e9ff7e"
libc = "musl"
os = "linux"

    [[Keyutils.download]]
    sha256 = "97a1e42ebbe1fecaab37977797d64de8c0b2f299f7d938da8e9e8d5ccb36404b"
    url = "https://github.com/JuliaBinaryWrappers/Keyutils_jll.jl/releases/download/Keyutils-v1.6.1+0/Keyutils.v1.6.1.i686-linux-musl.tar.gz"
[[Keyutils]]
arch = "i686"
git-tree-sha1 = "887bcbaf3209e35cc473101c6fb58073c1ddb962"
libc = "glibc"
os = "linux"

    [[Keyutils.download]]
    sha256 = "2d29a259e060062b49ce659bfb9b989d832e0c0c4c10bf76d0f278a3a59c60e1"
    url = "https://github.com/JuliaBinaryWrappers/Keyutils_jll.jl/releases/download/Keyutils-v1.6.1+0/Keyutils.v1.6.1.i686-linux-gnu.tar.gz"
[[Keyutils]]
arch = "powerpc64le"
git-tree-sha1 = "c5efb77f151a2d2da2151139b0049acf77d2709e"
libc = "glibc"
os = "linux"

    [[Keyutils.download]]
    sha256 = "7fdae07110d680d504df9eda936bb1160e80a7b7ebfd3d678122785093c3e9b8"
    url = "https://github.com/JuliaBinaryWrappers/Keyutils_jll.jl/releases/download/Keyutils-v1.6.1+0/Keyutils.v1.6.1.powerpc64le-linux-gnu.tar.gz"
[[Keyutils]]
arch = "armv7l"
git-tree-sha1 = "9e2d30441f5812d4ac818b573947ef6248046c19"
libc = "musl"
os = "linux"

    [[Keyutils.download]]
    sha256 = "ef919e642b90136fd42cb19d6013e21b152439431dc8ba19631aeb73b9fceb5c"
    url = "https://github.com/JuliaBinaryWrappers/Keyutils_jll.jl/releases/download/Keyutils-v1.6.1+0/Keyutils.v1.6.1.arm-linux-musleabihf.tar.gz"
[[Keyutils]]
arch = "aarch64"
git-tree-sha1 = "77dd4b540240ba9321650c9e965a08329906019e"
libc = "glibc"
os = "linux"

    [[Keyutils.download]]
    sha256 = "66467accf870f2d35eacf3f03d044b4f9e6e0fa652587a5a39802640bc5f2fc5"
    url = "https://github.com/JuliaBinaryWrappers/Keyutils_jll.jl/releases/download/Keyutils-v1.6.1+0/Keyutils.v1.6.1.aarch64-linux-gnu.tar.gz"
[[Keyutils]]
arch = "x86_64"
git-tree-sha1 = "be512e257ec48b18cfbf757bdb63179d624811ac"
libc = "glibc"
os = "linux"

    [[Keyutils.download]]
    sha256 = "5da1e57961982f7a810f65d3dacaf7adffa0a9fc5be6933443b010a02059c366"
    url = "https://github.com/JuliaBinaryWrappers/Keyutils_jll.jl/releases/download/Keyutils-v1.6.1+0/Keyutils.v1.6.1.x86_64-linux-gnu.tar.gz"
[[Keyutils]]
arch = "x86_64"
git-tree-sha1 = "436f2d29f158ab4506e9a86411c9432cc6eb6d24"
libc = "musl"
os = "linux"

    [[Keyutils.download]]
    sha256 = "0b0ac78edf96f27b89ea590fb3a602bdeb6f3aa6f3579b38116b56c6fc4eacad"
    url = "https://github.com/JuliaBinaryWrappers/Keyutils_jll.jl/releases/download/Keyutils-v1.6.1+0/Keyutils.v1.6.1.x86_64-linux-musl.tar.gz"
